spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    cache-period: 0

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
